language: node_js

node_js:
  - 8.10

before_install:
  - npm i -g npm@6.13.4

services:
  - docker

jobs:
  include:
  - stage: build
    script: npm run build
  - stage: docker
    script: npm run startDb
  - stage: stop_docker
    script: npm run stopDb
  - stage: test
    script: npm run test

stages:
  - build
  - docker
  - test
  - stop_docker

